# Generated by Django 3.2.18 on 2023-05-19 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='joined_user',
            field=models.ManyToManyField(blank=True, related_name='joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
