# Generated by Django 3.2.18 on 2023-05-17 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositoptions',
            name='fin_prdt_cd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deposits.depositproducts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositproducts',
            name='fin_prdt_cd',
            field=models.ManyToManyField(related_name='deposit_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
