# Generated by Django 3.2.18 on 2023-05-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230519_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deposit',
        ),
    ]
